import { db, markersTable } from "@workspace/db";
import { count, eq } from "drizzle-orm";
import { logger } from "./lib/logger";

const SEED_DATA = [
  // ── WINERIES: RUSSIAN RIVER VALLEY ───────────────────────────────────────
  { name: "Williams Selyem", note: "The benchmark Russian River Pinot. Allocation-heavy, appointment-only, and absolutely worth the effort. Old-vine purity at its finest.", category: "winery", lat: 38.5202, lng: -122.8670, website: "https://www.williamsselyem.com" },
  { name: "Kosta Browne", note: "World-class Pinot Noir with a lush, precise house style. Get an appointment if you can — this is a bucket-list tasting.", category: "winery", lat: 38.404975, lng: -122.819864, website: "https://www.kostabrowne.com" },
  { name: "Merry Edwards", note: "Old-vine Russian River Pinot royalty. Merry's wines are textbook Sonoma — elegant, cool-climate, endlessly drinkable.", category: "winery", lat: 38.4349, lng: -122.8549, website: "https://www.merryedwards.com" },
  { name: "Lynmar Estate", note: "Stunning Sebastopol estate with impeccable Pinot and Chardonnay. The grounds alone are worth the drive.", category: "winery", lat: 38.4423, lng: -122.8442, website: "https://www.lynmarwinery.com" },
  { name: "Gary Farrell", note: "Perched above the RRV with sweeping views. Single-vineyard Pinots that show exactly what this appellation can do.", category: "winery", lat: 38.5075, lng: -122.8974, website: "https://www.garyfarrellwinery.com" },
  { name: "Freeman Winery", note: "Intimate and unhurried. Redwood grove setting, cool wine cave, and Burgundian-inspired Pinots that reward attention.", category: "winery", lat: 38.4095, lng: -122.8831, website: "https://www.freemanwinery.com" },
  { name: "Littorai", note: "Biodynamic, Burgundian, and deeply serious. Ted Lemon's coastal Pinot and Chardonnay are among California's finest.", category: "winery", lat: 38.38484, lng: -122.865157, website: "https://www.littorai.com" },
  { name: "Paul Mathew Vineyards", note: "Meet the actual winemakers. Husband-and-wife operation in Graton pouring single-vineyard Pinots with old-world soul.", category: "winery", lat: 38.4346, lng: -122.8693, website: "https://paulmathewvineyards.com" },
  { name: "Pax Wine Cellars", note: "Downtown Sebastopol gem for Rhône-variety fanatics. The Syrah here is exceptional — buy a bottle and settle in.", category: "winery", lat: 38.4024, lng: -122.8271, website: "https://www.paxwines.com" },
  { name: "Landmark Vineyards", note: "Historic Kenwood tasting room with estate Chardonnay and Pinot. A reliable, refined stop without the appointment fuss.", category: "winery", lat: 38.4266, lng: -122.5562, website: "https://www.landmarkwine.com" },
  { name: "Domaine de la Rivière", note: "Relatively new but already collecting accolades. Pinot Noir and Chardonnay with old-world grace and genuine hospitality.", category: "winery", lat: 38.5297, lng: -122.7999, website: "https://www.domaineriviere.com" },

  // ── WINERIES: SONOMA VALLEY ───────────────────────────────────────────────
  { name: "Benziger Family Winery", note: "The essential biodynamic stop in Glen Ellen. The tram tour actually teaches you something, and the setting is gorgeous.", category: "winery", lat: 38.3608, lng: -122.5428, website: "https://www.benziger.com" },
  { name: "Imagery Estate Winery", note: "Artist-label wines, a working art gallery, and a patio that doesn't feel like a tourist trap. Underrated and worth it.", category: "winery", lat: 38.3601, lng: -122.5037, website: "https://www.imagerywinery.com" },
  { name: "Gundlach Bundschu", note: "California's oldest family winery. \"Gun Bun\" does it right — beautiful grounds, great events, and an underrated Gewürztraminer.", category: "winery", lat: 38.280768, lng: -122.41711, website: "https://www.gunbun.com" },
  { name: "Scribe Winery", note: "Hacienda vibes near Sonoma Plaza, excellent pét-nat and sparkling, and a food program built around the land.", category: "winery", lat: 38.271284, lng: -122.423063, website: "https://www.scribewinery.com" },
  { name: "Buena Vista Winery", note: "California's first premium winery (1857). The history alone is worth a visit, and the wines hold their own.", category: "winery", lat: 38.2995, lng: -122.4220, website: "https://www.buenavistawinery.com" },
  { name: "Chateau St. Jean", note: "1920s chateau grandeur in Kenwood. Award-winning wines, manicured grounds, and breathtaking mountain views.", category: "winery", lat: 38.4237, lng: -122.5539, website: "https://www.chateaustjean.com" },
  { name: "B. Wise Winery", note: "A cave tasting experience unlike anything else — dramatic barrel-vaulted tunnels in the Moon Mountain District.", category: "winery", lat: 38.415646, lng: -122.548062, website: "https://www.bwisevineyards.com" },
  { name: "Repris Winery", note: "The Moon Mountain ATV tour is as memorable as the wine. Cabernet planted in the 1880s. Rare and remarkable.", category: "winery", lat: 38.345924, lng: -122.458795, website: "https://repriswines.com" },
  { name: "Three Sticks Wines", note: "Pre-Gold Rush adobe setting from 1842. Designed by Ken Fulk with the ambience of another era. Pinot and Chard.", category: "winery", lat: 38.2924, lng: -122.4589, website: "https://www.threestickswines.com" },
  { name: "Hamel Family Wines", note: "Certified biodynamic, dry-farmed since 2018. Cave tours, library tastings, Bordeaux-style blends. Appointment only.", category: "winery", lat: 38.345814, lng: -122.494018, website: "https://www.hamelfamilywines.com" },
  { name: "Hanzell Vineyards", note: "Founded in 1953 by an ambassador inspired by Burgundy. Bird's-eye Sonoma Valley views and benchmark Chardonnay.", category: "winery", lat: 38.3111, lng: -122.4630, website: "https://www.hanzell.com" },
  { name: "Viansa Winery", note: "Tuscan-inspired estate with Italian varietals, a deli marketplace, and picnic tables overlooking the valley.", category: "winery", lat: 38.20847, lng: -122.451805, website: "https://www.viansa.com" },
  { name: "Mayo Family Winery", note: "Absurd value for a deep-dive tasting in Kenwood. Many wines, attentive pours, zero pretension. A local secret.", category: "winery", lat: 38.4185, lng: -122.5488, website: "https://www.mayofamilywinery.com" },
  { name: "St. Francis Winery", note: "Certified Sustainable family-owned estate. The food and wine pairing experience here is among Sonoma's best.", category: "winery", lat: 38.4080, lng: -122.5568, website: "https://www.stfranciswinery.com" },
  { name: "Coursey Graves", note: "French-inspired at 1,500 feet on Bennett Mountain. Panoramic views, Monet-style gardens, and luxury private tastings.", category: "winery", lat: 38.4000405, lng: -122.604536, website: "https://www.courseygraves.com" },

  // ── WINERIES: DRY CREEK VALLEY ───────────────────────────────────────────
  { name: "Ferrari-Carano Vineyards", note: "Villa grandeur in Dry Creek. Stately rose gardens, early tastings, and a Fumé Blanc that earns its reputation.", category: "winery", lat: 38.5647, lng: -122.8669, website: "https://www.ferrari-carano.com" },
  { name: "Mauritson Wines", note: "Sixth-generation family Zinfandel. Honest, direct, and exactly what Dry Creek Valley should taste like.", category: "winery", lat: 38.6504, lng: -122.9120, website: "https://www.mauritsonwines.com" },
  { name: "Truett Hurst", note: "Biodynamic holistic farm with goats, sheep, chickens, and great Zinfandel. The eco-estate tour is a genuine delight.", category: "winery", lat: 38.606292, lng: -122.86246, website: "https://www.truetthurst.com" },
  { name: "Preston Farm & Winery", note: "No tour needed — winemaking operations visible in the courtyard. Feels like a European village bodega. Old-school cool.", category: "winery", lat: 38.7030, lng: -122.9674, website: "https://www.prestonfarmandwinery.com" },
  { name: "Quivira Vineyards", note: "Biodynamic Dry Creek estate with certified-organic farming and a standout Zinfandel built on Rhône sensibility.", category: "winery", lat: 38.655807, lng: -122.936371, website: "https://www.quivirawine.com" },
  { name: "Dry Creek Vineyard", note: "The original Dry Creek label — and it shows. Consistent, honest, and the Fumé Blanc is a perennial benchmark.", category: "winery", lat: 38.6529, lng: -122.9240, website: "https://www.drycreekvineyard.com" },
  { name: "Mounts Family Winery", note: "Tiny family operation where you might meet the winemaker. Rare varietals, bocce court, local vibes.", category: "winery", lat: 38.657683, lng: -122.94432, website: "https://www.mountswinery.com" },
  { name: "Ridge Lytton Springs", note: "Old-vine Zinfandel from one of California's most respected names. The Lytton Springs site is historic and essential.", category: "winery", lat: 38.6591, lng: -122.8858, website: "https://www.ridgewine.com" },

  // ── WINERIES: ALEXANDER VALLEY ───────────────────────────────────────────
  { name: "Jordan Winery", note: "The Alexander Valley estate that defined restrained California Cabernet. Stunning chateau, impeccable hospitality, and the best library tasting in the county.", category: "winery", lat: 38.661639, lng: -122.85018, website: "https://www.jordanwinery.com" },
  { name: "Francis Ford Coppola Winery", note: "Part winery, part resort — pools, bocce, Hollywood memorabilia. Great for groups and a genuinely fun afternoon.", category: "winery", lat: 38.6794, lng: -122.8875, website: "https://www.francisfordcoppolawinery.com" },
  { name: "Stonestreet Estate", note: "Mountain estate Cabernet at its Sonoma best. The Alexander Mountain terroir produces power with elegance.", category: "winery", lat: 38.669294, lng: -122.812386, website: "https://www.stonestreetwines.com" },
  { name: "Chalk Hill Estate", note: "1,300-acre estate with stunning views, warm hospitality, and terroir-driven Chardonnay that punches above its price.", category: "winery", lat: 38.568223, lng: -122.771005, website: "https://www.chalkhill.com" },
  { name: "Medlock Ames", note: "Modern rural-hipster done right. Founded by two college friends in 1998 with organic farming at the center.", category: "winery", lat: 38.6664533, lng: -122.8222575, website: "https://www.medlockames.com" },
  { name: "Banshee Wines", note: "Geyserville estate tasting room in Alexander Valley. Pinot and vinyl — select your record, pour your wine, vibe out.", category: "winery", lat: 38.682145, lng: -122.835281, website: "https://www.bansheewines.com" },

  // ── WINERIES: HEALDSBURG ─────────────────────────────────────────────────
  { name: "Seghesio Family Vineyards", note: "The Healdsburg Zinfandel standard. Multi-generational, Italian-rooted, and pours with the ease of family confidence.", category: "winery", lat: 38.6175, lng: -122.8754, website: "https://www.seghesio.com" },
  { name: "Locals Tasting Room", note: "One tasting room, seven small producers. The smartest first stop in Geyserville for scoping what you want to pursue.", category: "winery", lat: 38.7065, lng: -122.9041, website: "https://www.localstastingroom.com" },
  { name: "Bricoleur Vineyards", note: "Stunning RRV estate south of Healdsburg. Picnic wagons, bocce, rose gardens, and consistently elegant wines.", category: "winery", lat: 38.5249, lng: -122.8314, website: "https://www.bricoleurvineyards.com" },
  { name: "J Vineyards & Winery", note: "Top California sparkling wine producer. The Bubble Room five-course pairing is a legitimate destination dining experience.", category: "winery", lat: 38.5729, lng: -122.8424, website: "https://www.jwine.com" },
  { name: "Zina Hyde Cunningham Winery", note: "Sunset patio, fireplace inside, cheese boards, and intimate Sonoma Plaza tastings. The evening wind-down.", category: "winery", lat: 38.2919, lng: -122.4561, website: "https://www.zinawinery.com" },

  // ── WINERIES: CARNEROS / PETALUMA ────────────────────────────────────────
  { name: "The Donum Estate", note: "50+ monumental sculptures on 200 acres plus world-class Pinot and Chardonnay. Art and wine in full Carneros elegance.", category: "winery", lat: 38.2305, lng: -122.4017, website: "https://www.thedonumestate.com" },
  { name: "Schug Carneros Estate", note: "German-born winemaker Walter Schug's legacy estate. Benchmark Carneros Pinot and Chardonnay in a quiet setting.", category: "winery", lat: 38.2307, lng: -122.4767, website: "https://www.schugwinery.com" },
  { name: "Region Wine Bar", note: "Downtown Sebastopol's finest pour. 50+ wines by the taste via self-pour machines. The ideal first stop before any winery day.", category: "restaurant", lat: 38.404153, lng: -122.819711, website: "https://drinkregion.com" },

  // ── RESTAURANTS: HEALDSBURG ───────────────────────────────────────────────
  { name: "SingleThread", note: "Kyle and Katina Connaughton's 3-Michelin-star omakase — eleven courses built on their farm behind the restaurant. The most serious table in Sonoma County.", category: "restaurant", lat: 38.6123, lng: -122.8697, website: "https://www.singlethreadfarms.com" },
  { name: "Valette", note: "Dustin Valette's flagship on Center Street — the room that put Healdsburg's culinary identity on the map. Deep Sonoma sourcing, honest technique, and hospitality that doesn't feel performed.", category: "restaurant", lat: 38.6121, lng: -122.8696, website: "https://www.valettehealdsburg.com" },
  { name: "Troubadour / Le Dîner", note: "A 7-course Michelin-listed tasting menu hidden inside a 20-seat bakery — SingleThread alumni running an extraordinary Thursday-through-Sunday dinner. Prepaid on Tock, no walk-ins. Book before you leave home.", category: "restaurant", lat: 38.6115, lng: -122.8710, website: "https://www.troubadourhbg.com" },
  { name: "Juju's — French-Moroccan Pop-Up at Acorn Cafe", note: "Chef Jason Pringle cooking from his 97-year-old grandmother's recipes in a borrowed plaza café Thu–Sun evenings. Lamb shank tagine, poulet rôti with harissa potatoes, cheese cappelletti with beet and Meyer lemon. Nothing else like it in the county right now.", category: "restaurant", lat: 38.6105, lng: -122.8690, website: null },
  { name: "Folia Bar & Kitchen — Appellation Healdsburg", note: "Reed Palmer's three-course prix fixe at one of Wine Country's most striking new resort properties. Mt. Lassen trout, Mary's chicken, estate garden vegetables. The rooftop bar and panoramic plaza views earn a stop on their own.", category: "restaurant", lat: 38.6105, lng: -122.8692, website: "https://www.appellationhotels.com/hotels/california-healdsburg/dining/folia-bar-kitchen/" },
  { name: "Bistro Lagniappe", note: "The downtown Healdsburg table that's open seven nights a week — including Mondays when almost nothing else is. French-California comfort in a warm room that feels like it belongs to the town.", category: "restaurant", lat: 38.6116, lng: -122.8705, website: "https://www.lagniappehealdsburg.com" },
  { name: "The Matheson", note: "Dustin Valette's rooftop bar and restaurant on the plaza — three floors, a wood-fired kitchen, and the best view in downtown Healdsburg. The cocktail program is serious.", category: "restaurant", lat: 38.6102, lng: -122.8700, website: "https://www.thematheson.com" },
  { name: "Barndiva", note: "A beautiful garden room in the middle of Healdsburg — seasonal farm-to-table cooking in a converted barn with genuine warmth. The Saturday brunch with live music in the garden is one of the better weekend mornings in the county.", category: "restaurant", lat: 38.6096, lng: -122.8695, website: "https://www.barndiva.com" },
  { name: "Little Saint", note: "The Moshin family's plant-based restaurant and market on the plaza — genuinely inventive cooking that doesn't position itself as a compromise. Good for the table with mixed preferences.", category: "restaurant", lat: 38.6120, lng: -122.8719, website: "https://www.littlesainthealdsburg.com" },
  { name: "Baci Café & Wine Bar", note: "The one reliable dinner in downtown Healdsburg on a Monday. Italian classics, good pasta, a wine list full of Sonoma County names, and neighborhood ease when nothing else is open.", category: "restaurant", lat: 38.6117, lng: -122.8706, website: "https://www.bacicafeandwinebar.com" },
  { name: "Acorn Cafe", note: "Breakfast and brunch anchor on the Healdsburg Plaza — the right start for any Healdsburg food day. After hours Thu–Sun it becomes Juju's French-Moroccan pop-up.", category: "restaurant", lat: 38.6105, lng: -122.8690, website: null },
  { name: "Dry Creek Kitchen", note: "Charlie Palmer's flagship Healdsburg restaurant anchoring Hotel Healdsburg — Sonoma sourcing, wine-country ambience, and one of the most reliable kitchens on the plaza.", category: "restaurant", lat: 38.6108, lng: -122.8711, website: "https://drycreekkitchen.com" },
  { name: "Willi's Seafood & Raw Bar", note: "Mark and Terri Stark's lively raw bar on North Healdsburg Ave — oysters, crudo, ceviches, and tapas-style seafood plates in a room that never loses energy. The oyster happy hour is one of the best value stops in the county.", category: "restaurant", lat: 38.6120, lng: -122.8712, website: "https://www.starkrestaurants.com/willis-seafood" },
  { name: "Bravas Bar de Tapas", note: "The Stark group's Spanish tapas room on Center St — patatas bravas, croquetas, razor clams, and a sherry list that doesn't apologize for itself. The ideal pre- or post-winery hang in Healdsburg.", category: "restaurant", lat: 38.6129, lng: -122.8698, website: "https://www.starkrestaurants.com/bravas" },

  // ── RESTAURANTS: ALEXANDER VALLEY / GEYSERVILLE ───────────────────────────
  { name: "Jimtown Store", note: "The historic 1895 country store tucked into the Alexander Valley vines on Highway 128. Fresh-prepared food, homebaked goods, famous chocolate pudding, and the perfect anchor for any Alexander Valley wine day. Open Mondays — rare on this corridor.", category: "restaurant", lat: 38.6688, lng: -122.8172, website: "https://www.jimtown.com" },
  { name: "Cyrus", note: "Douglas Keane's multi-act dining experience in Geyserville — champagne and canapés, interactive chef's table, main dining room, and a dessert room with a molten chocolate fountain. The Sunday Family Meal ($55 gochujang fried chicken) and Kisetsu Ramen popup are easier ways in.", category: "restaurant", lat: 38.7073, lng: -122.9018, website: "https://www.cyrusrestaurant.com" },
  { name: "Diavola", note: "The loud, delicious Geyserville table for pizza, pasta, and house-cured salumi. Chef Dino Bugica has been making charcuterie and working that wood oven for years without losing the plot. The best stop after a Dry Creek or Alexander Valley wine day.", category: "restaurant", lat: 38.7063, lng: -122.9041, website: "https://www.diavolapizzeria.com" },

  // ── RESTAURANTS: KENWOOD / GLEN ELLEN ────────────────────────────────────
  { name: "Stella", note: "Ari Weiswasser and chef de cuisine Bryant Minuche's Italian-California room in the old Cafe Citti space, opened March 2025. Roman tonnarelli, lumache with spring pea pesto, burrata with 12-year balsamic. Open every night including Mondays — exceptional on this corridor.", category: "restaurant", lat: 38.4181, lng: -122.5503, website: null },
  { name: "Glen Ellen Star", note: "Ari Weiswasser's original wood-fired room in Glen Ellen — the table that put the Sonoma Valley back on the serious food map. Brick chicken, ember-roasted vegetables, produce from the farm behind the restaurant.", category: "restaurant", lat: 38.3643, lng: -122.5246, website: "https://www.glenellenstar.com" },
  { name: "Poppy", note: "The Girl & The Fig's Sondra Bernstein and John Toulze transformed the old Fig Café into this French countryside room in May 2025. Crispy poulet rôti, Coquilles Saint-Jacques, asparagus salad with Sonoma strawberries. Wed–Fri prix fixe includes wine.", category: "restaurant", lat: 38.3635, lng: -122.5246, website: null },

  // ── RESTAURANTS: SONOMA TOWN ──────────────────────────────────────────────
  { name: "Enclos", note: "Two Michelin stars and a Green Star in its first year — chef Brian Limoges (Quince, Atelier Crenn) inside a restored 1880 Victorian half a block from Sonoma Plaza. The 11-course tasting menu is grounded in Stone Edge Farm's organic gardens. The hottest reservation in Northern California right now.", category: "restaurant", lat: 38.2916, lng: -122.4558, website: "https://enclos-sonoma.com" },
  { name: "Rosso Pizzeria — Sonoma Plaza", note: "Wood-fired pizza, good salads, and the fried chicken with smashed potatoes that people drive across the county for. A Sonoma institution with honest prices.", category: "restaurant", lat: 38.2921, lng: -122.4561, website: "https://www.rossopizzeria.com" },

  // ── RESTAURANTS: PETALUMA ─────────────────────────────────────────────────
  { name: "Bijou", note: "Chef Stéphane Saint Louis (Table Culture Provisions) opened this French bistro in the former Easy Rider space in June 2025. Steak frites with sauce au poivre, cod brandade croquettes, and gâteau St. Honoré from pastry chef Sylvain Parsy. Open Mondays — almost unique at this quality level.", category: "restaurant", lat: 38.2355, lng: -122.6418, website: null },
  { name: "Table Culture Provisions", note: "The Michelin-recognized 7-course tasting menu from chefs Stéphane Saint Louis and Steven Vargas — Michelin-level cooking at neighborhood prices. Social Hour Wed–Thu 4–6 PM offers à la carte access. Nothing else like it in the county.", category: "restaurant", lat: 38.2316, lng: -122.6351, website: "https://www.tcprovision.com" },
  { name: "Seared", note: "Petaluma's anchor for steak, seafood, and barrel-aged cocktails — Beeman Ranch beef, line-caught halibut, and a wine list leaning Sonoma County. The hanger steak with truffled parmesan frites is the order.", category: "restaurant", lat: 38.2355, lng: -122.6407, website: "https://www.searedpetaluma.com" },
  { name: "Della Fattoria", note: "The family-owned Petaluma bakery whose bread shows up on half the menus in the county. The rosemary boule and wood-fired breads are reasons to detour off the 101. Breakfast and lunch daily; dinner Thu–Sat. Eat the bread at the source.", category: "restaurant", lat: 38.2350, lng: -122.6409, website: "https://www.dellafattoria.com" },
  { name: "The Shuckery", note: "Bohemian's Best Oyster Room two years running, inside the historic Hotel Petaluma. Chef Matt Meyer and Jazmine Lalicker run an oyster-forward room with a wine list that won Best in Sonoma County. Spring is peak season for Tomales Bay oysters.", category: "restaurant", lat: 38.2356, lng: -122.6422, website: "https://www.theshuckeryca.com" },
  { name: "Lagunitas Brewing Company", note: "The flagship Lagunitas taproom in Petaluma — open-air seating, live music calendar, rotating one-off brews from the on-site Disorderly House brewhouse. Jumbo Bavarian pretzel and smoked chicken wings are the food orders. Bring the dog. Open daily.", category: "restaurant", lat: 38.2721, lng: -122.6627, website: "https://www.lagunitas.com" },

  // ── RESTAURANTS: SEBASTOPOL / WEST COUNTY ────────────────────────────────
  { name: "Goldfinch", note: "Modern American bistro cooking around an open wood fire in Sebastopol's Livery on Main — chef Rodrigo Mendoza's seasonal, local, polished room. One of the strongest additions to the Sebastopol dining scene in years. Open Mondays.", category: "restaurant", lat: 38.4019, lng: -122.8238, website: null },
  { name: "Acre Pasta", note: "House-made pasta every morning, honest prices, and a rotating menu that takes the produce seriously. Spaghetti with Sunday red sauce at $12. The lumache with porcini cream is the sleeper hit.", category: "restaurant", lat: 38.4038, lng: -122.8203, website: null },
  { name: "Ramen Gaijin", note: "House-made noodles, serious broth, and an izakaya menu built around local ingredients and Japanese technique. Happy hour 2:30–4:30 PM Tue–Sat. The broth tastes like someone spent two days on it.", category: "restaurant", lat: 38.4025, lng: -122.8237, website: "https://www.ramengaijin.com" },
  { name: "Fern Bar", note: "Modern American food, genuinely excellent zero-proof cocktails, spirits, and live music in a plant-filled Barlow room. Happy hour daily 3–5 PM. The best long hang in Sebastopol — and the best non-alcoholic cocktail program in the county.", category: "restaurant", lat: 38.4033, lng: -122.8212, website: "https://www.fernbar.com" },
  { name: "Handline", note: "Sustainable seafood with a seasonal porch that's one of the best outdoor happy-hour spots in West County. A communal table under a giant live oak, soft-serve ice cream, and kids welcome. Smoked trout chowder and fish tacos are the orders.", category: "restaurant", lat: 38.3923, lng: -122.8174, website: "https://www.handline.com" },
  { name: "Underwood Bar and Bistro", note: "The longtime West County anchor in the tiny village of Graton — steak frites, flatbreads, a serious bar. The flat iron steak frites with mushroom-shallot butter and chipotle sauce has earned its place on the permanent menu.", category: "restaurant", lat: 38.4363, lng: -122.8687, website: "https://www.underwoodgraton.com" },

  // ── RESTAURANTS: SANTA ROSA ───────────────────────────────────────────────
  { name: "Rosso Pizzeria — Santa Rosa", note: "The beloved Sonoma pizza institution — wood-fired pizza program and a fried chicken with smashed potatoes and caramelized pancetta that is already among the best casual bites in the county.", category: "restaurant", lat: 38.4422, lng: -122.7035, website: "https://www.rossopizzeria.com" },
  { name: "Augie's French", note: "Mark and Terri Stark's lively French bistro on 4th Street — steak frites, mussels, classic bistro sauces, and a room built for date nights and small groups. The wine list tilts French and local, which is exactly right.", category: "restaurant", lat: 38.4403, lng: -122.7147, website: "https://www.starkrestaurants.com/augies" },
  { name: "Bird & The Bottle", note: "The Santa Rosa table for shareable plates, a busy bar, and wood-fired cooking. Best with a group that wants to order widely and pass everything around the table. One of Santa Rosa's most reliable rooms. Open Mondays.", category: "restaurant", lat: 38.4445, lng: -122.7057, website: "https://www.starkrestaurants.com/bird-the-bottle" },
  { name: "Stark's Steak & Seafood", note: "The Santa Rosa anchor for serious steak — Beeman Ranch beef, a wine list that leans Sonoma, and a happy hour that regulars treat as a standing appointment. The $6 martini on Tuesdays is the local secret.", category: "restaurant", lat: 38.4389, lng: -122.7232, website: "https://www.starkrestaurants.com/starks" },
  { name: "Grata Italian Eatery", note: "Chef-owner Eric Foster's Italian kitchen — one of the most underappreciated rooms in north Sonoma County. House-made gnudi, burrata with preserved lemon honey, caramelized pear and endive bruschetta. Open Mondays.", category: "restaurant", lat: 38.5472, lng: -122.8127, website: null },
  { name: "Willi's Wine Bar", note: "The Stark group's original and arguably their most beloved — 40-plus wines by the glass, a small-plates menu built for grazing, and a warm room that rewards repeat visits. The anchor of the Old Redwood Hwy food corridor north of Santa Rosa.", category: "restaurant", lat: 38.4925, lng: -122.7423, website: "https://www.starkrestaurants.com/willis-wine-bar" },

  // ── RESTAURANTS: FORESTVILLE / RUSSIAN RIVER ──────────────────────────────
  { name: "BaSo Annex (Bazaar Sonoma)", note: "After fire hit the original Bazaar Sonoma, chef Sean Quan and Jenny Phan opened an interim café with their best dishes — zhong dumplings with house chili crisp, Taiwan braised pork rice, mapo tofu. Prices $9–$24. One of the most interesting kitchens in the county at the most honest price point.", category: "restaurant", lat: 38.4735, lng: -122.8920, website: null },
  { name: "Farmhouse Inn Restaurant", note: "New à la carte format as of March 2026 under chef Julio Aguilera — upscale casual cooking in one of the RRV's most beautiful properties. Burrata, Caesar, grilled broccolini, steak with pommes purée and lobster butter.", category: "restaurant", lat: 38.4893, lng: -122.8833, website: "https://www.farmhouseinn.com" },
  { name: "boon eat + drink", note: "Crista Luedtke's farm-to-table California bistro anchoring Guerneville's food scene since 2009. Primarily organic, a house garden, and a menu that genuinely shifts with the season. The anchor of a good Guerneville evening.", category: "restaurant", lat: 38.5022, lng: -122.9984, website: "https://eatatboon.com" },

  // ── RESTAURANTS: SONOMA COAST / POINT REYES ───────────────────────────────
  { name: "Terrapin Creek Cafe", note: "Michelin-recognized in Bodega Bay with a kitchen that punches far above its coastal roadside setting. Pan-roasted Hokkaido scallops with sunchoke purée, charred octopus, Mediterranean fish stew. Open Mondays.", category: "restaurant", lat: 38.3391, lng: -123.0482, website: "https://www.terrapincreekcafe.com" },
  { name: "Rocker Oysterfeller's", note: "Southern comfort on Highway 1 in Valley Ford — grassfed smashburgers, buttermilk fried chicken with Lagunitas ale and caraway gravy, and Tomales Bay oysters raw or grilled. Dollar Oyster Mondays all day.", category: "restaurant", lat: 38.3178, lng: -122.9245, website: "https://www.rockeroysterfellers.com" },
  { name: "Saltwater Oyster Depot", note: "Reservation-only dinners in a small coastal room in Inverness across from Tomales Bay. Tomales Bay oysters and locally sourced seafood, prepared with care and without pretension. Open Mondays for dinner.", category: "restaurant", lat: 38.0966, lng: -122.8521, website: "https://www.saltwateroysterdepot.com" },
  { name: "Hog Island Oyster Boat Bar", note: "The outdoor oyster table right on the water in Marshall — raw oysters, BBQ oysters, and Tomales Bay as your setting. Reservations required; standby fills fast. No better version of this experience exists in Northern California.", category: "restaurant", lat: 38.1622, lng: -122.8937, website: "https://hogislandoysters.com/restaurants/marshall/" },
  { name: "Nick's Cove", note: "Sustainable coastal cooking from Marin and Sonoma farms in one of the best bay settings on the California coast. Live music through spring. Good for a solo lunch, a date dinner, or a group with a shared love of the coastline.", category: "restaurant", lat: 38.1995, lng: -122.9206, website: "https://www.nickscove.com" },
  { name: "Station House Cafe", note: "The newly renovated community anchor in Point Reyes Station — local, seasonal, and relaxed in the best way. Live music and specials through the spring calendar. A place that actually belongs to its town.", category: "restaurant", lat: 38.0681, lng: -122.8062, website: "https://www.stationhousecafe.com" },

  // ── FARMSTANDS ────────────────────────────────────────────────────────────
  { name: "Cloverdale Certified Farmers Market", note: "Community-built certified market at the heart of Alexander Valley wine country — Sundays April through November. Local farmers, food purveyors, and craft. CalFresh/Market Match accepted. The most local market in the northern coverage area.", category: "farmstand", lat: 38.7985, lng: -122.9838, website: "https://www.farmtrails.org" },
  { name: "Healdsburg Certified Farmers Market", note: "One of California's original 22 certified markets, running since 1978. Most produce grown within 10 miles of the plaza. Saturdays April–December and Tuesdays May–September. Wild fish, pasture-finished meat, heirloom vegetables, baked goods.", category: "farmstand", lat: 38.6116, lng: -122.8697, website: "https://www.healdsburgfarmersmarket.org" },
  { name: "Journeyman Meat Co.", note: "John Stewart and Duskie Estes' whole-hog salumi operation on Center Street — heritage-breed pork sourced from farms they know by name, cured and smoked on-site. The coppa, guanciale, and fennel salami are the real thing. One of the very few places in Sonoma County producing genuine charcuterie at this level.", category: "farmstand", lat: 38.612404, lng: -122.869757, website: "https://journeymanmeat.com" },
  { name: "Dry Creek Peach & Produce", note: "The last dedicated organic peach orchard in Dry Creek Valley — thirty-plus varieties of white and yellow peaches, tree-ripened, hand-picked, hand-packed. Open July through early September. Alice Waters named one of their varieties her last-supper pick.", category: "farmstand", lat: 38.699729, lng: -122.957231, website: "https://www.drycreekpeach.com" },
  { name: "SingleThread Farm Store", note: "Kyle and Katina Connaughton's working farm behind the 3-Michelin-star restaurant — open to the public Thu–Sun. The same produce, flowers, and pantry items grown for the restaurant kitchen. The only place in the county where you can buy what a 3-star kitchen grows.", category: "farmstand", lat: 38.647165, lng: -122.913057, website: "https://www.singlethreadfarms.com" },
  { name: "Front Porch Farm", note: "Organic flower and vegetable farm along the Russian River — sixty-plus flower varieties, u-pick Saturdays, river picnic access with all materials provided. The prettiest u-pick in northern Sonoma County.", category: "farmstand", lat: 38.6185, lng: -122.8319, website: "https://www.fpfarm.com" },
  { name: "Windsor Certified Farmers Market", note: "50-plus vendors on the Town Green — Sundays April through December, plus Thursday Summer Nights June–August. Certified organic produce, artisan bakeries, cheeses, seasonal produce festivals, and live music every week.", category: "farmstand", lat: 38.5477, lng: -122.8133, website: "https://www.windsorfarmersmarket.com" },
  { name: "Wise Acre Farm — Egg Vending Machine", note: "Tiffany Holbrook's free-range egg farm stocks California's first farm egg vending machine 24/7 with a rainbow of varieties. Grade AA, CA SEFS compliant. Also at Healdsburg Saturday Market in summer. Yes, it's exactly what it sounds like.", category: "farmstand", lat: 38.563202, lng: -122.812501, website: "https://www.farmtrails.org" },
  { name: "Santa Rosa Original Certified Farmers Market", note: "The oldest and largest farmers market in Sonoma County — running continuously since 1967. Sixty-five-plus local farmers every Saturday at the Luther Burbank Center for the Arts. Voted Best Farmers Market in Sonoma County year after year. Slow Food Snail of Approval.", category: "farmstand", lat: 38.49338, lng: -122.748927, website: "https://www.thesantarosafarmersmarket.com" },
  { name: "Santa Rosa Community Farmers Market", note: "A second year-round certified market in Santa Rosa at Farmers Lane Plaza — Wednesdays and Saturdays. More relaxed than the Luther Burbank flagship, strong neighborhood following. CalFresh/Market Match accepted.", category: "farmstand", lat: 38.4333, lng: -122.6891, website: "https://www.farmtrails.org" },
  { name: "Tierra Vegetables Farmstand", note: "Wayne and Lee James have farmed this suburban Santa Rosa plot since 1980 and sell only what they grow — 30-plus varieties of heirloom dried beans, masa from heirloom corn, fresh and dried chiles, and pantry staples. The heirloom bean selection alone is worth a special trip.", category: "farmstand", lat: 38.511664, lng: -122.771735, website: "https://www.farmtrails.org" },
  { name: "Sebastopol Certified Farmers Market", note: "Every Sunday regardless of season — the best Sunday morning ritual in West County. First strawberries, snap peas, and asparagus start arriving in March. Sits on the West County Regional Trail. Produce arrives fast and the crowd thins by 11.", category: "farmstand", lat: 38.4024, lng: -122.8236, website: "https://www.sebastopolfarmersmarket.org" },
  { name: "Redwood Hill Farm / Capracopia", note: "Regenerative goat dairy with hands-on cheesemaking farm tours — spring is baby goat season, the best time to visit. Small farmstand carries olive oil, goat milk soaps, and cut flowers. The spring tours are legitimately joyful.", category: "farmstand", lat: 38.424036, lng: -122.849937, website: "https://redwoodhillfarm.org" },
  { name: "Gold Ridge Organic Farms", note: "Heritage apple varieties direct from the orchard, plus fresh-pressed olive oil in fall — watch it flow from the press on-site in October. Annual Apple Blossom Festival in spring. One of the last heritage apple operations in the region.", category: "farmstand", lat: 38.4087, lng: -122.9190, website: "https://www.farmtrails.org" },
  { name: "EARTHseed Farm", note: "California's first Afro-Indigenous permaculture farm, founded by Pandora Thomas. U-pick days, guided farm tours, farm stays, and a seasonal farm store. Celebrates African agricultural traditions through regenerative practices. Unlike any other farm experience in the county.", category: "farmstand", lat: 38.4377, lng: -122.8800, website: "https://www.earthseedfarm.org" },
  { name: "Forestville Certified Farmers Market", note: "Tuesday evenings June through late August under the oak trees in downtown Forestville — live music, wine, cold beer, and farm-fresh produce alongside the West County Regional Trail. One of the most atmospheric small markets in the county.", category: "farmstand", lat: 38.4736, lng: -122.8983, website: "https://www.farmtrails.org" },
  { name: "Guerneville Certified Farmers Market", note: "Thursday evenings June through August behind St. Hubert's Hall — operated by the same group as the Santa Rosa Original, with the same Slow Food Snail of Approval. The Russian River crowd is its own thing. A summer Thursday here has a completely different energy from any other market in the county.", category: "farmstand", lat: 38.5027, lng: -122.9977, website: "https://www.farmtrails.org" },
  { name: "Occidental Community Farmers Market", note: "Thursday evenings May through October on Main Street in this tiny redwood-hills hamlet — fresh produce, prepared foods, crafts, and live music in a setting unlike any other market in the region. There is no better Thursday evening in West County.", category: "farmstand", lat: 38.4077, lng: -122.9418, website: "https://www.farmtrails.org" },
  { name: "The Fork at Point Reyes Farmstead Cheese", note: "A reservation-only food experience on one of the county's most beautiful working dairy farms. Spring is the best season for fresh chèvre and young cheeses. This is what farm-to-table actually feels like — an actual farm, with cows, a cheese cave, and a story you can eat.", category: "farmstand", lat: 38.097813, lng: -122.832019, website: "https://www.pointreyescheese.com" },
];

export async function seedIfEmpty() {
  try {
    const [row] = await db.select({ count: count() }).from(markersTable);
    const existing = Number(row?.count ?? 0);

    if (existing === 0) {
      logger.info("Database is empty — seeding initial data...");
      const result = await db.insert(markersTable).values(SEED_DATA).returning({ name: markersTable.name });
      logger.info({ count: result.length }, "Seed complete");
      return;
    }

    // Insert any new seed entries not yet in the database
    const rows = await db.select({ name: markersTable.name }).from(markersTable);
    const existingNames = new Set(rows.map((r) => r.name));
    const missing = SEED_DATA.filter((s) => !existingNames.has(s.name));
    if (missing.length > 0) {
      const result = await db.insert(markersTable).values(missing).returning({ name: markersTable.name });
      logger.info({ count: result.length, names: result.map((r) => r.name) }, "Inserted new seed entries");
    } else {
      logger.info({ existing }, "Database already seeded — skipping");
    }
  } catch (err) {
    logger.error({ err }, "Seed failed — continuing without seeding");
  }
}

export async function correctCoordinates() {
  try {
    logger.info("Correcting marker coordinates and websites to verified data...");
    let updated = 0;
    for (const spot of SEED_DATA) {
      const result = await db
        .update(markersTable)
        .set({ lat: spot.lat, lng: spot.lng, website: spot.website ?? null })
        .where(eq(markersTable.name, spot.name))
        .returning({ id: markersTable.id });
      updated += result.length;
    }
    logger.info({ updated }, "Coordinate and website correction complete");
  } catch (err) {
    logger.error({ err }, "Coordinate correction failed");
  }
}
